name: Trigger Netlify Build
on:
  schedule:
    - cron: '0,30 16,17,18 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6010170933dced1b01733085